services:
  - type: web
    name: visioncloud-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: AWS_REGION
        value: ca-central-1
      - key: S3_BUCKET
        value: visionindex-achebe
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
    healthCheckPath: /api/health

  - type: web
    name: visioncloud-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        fromService:
          name: visioncloud-backend
          type: web
          property: hostport
    dependsOn:
      - visioncloud-backend
