apiVersion: v1
kind: Service
metadata:
  name: visioncloud-backend
  namespace: visioncloud
spec:
  selector:
    app: visioncloud-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
