apiVersion: v1
kind: ConfigMap
metadata:
  name: visioncloud-config
  namespace: visioncloud
data:
  AWS_REGION: "ca-central-1"
  S3_BUCKET: "visionindex-achebe"
  QUALITY_THRESHOLD: "0.5"
  UPSCALE_SCALE: "2"
