apiVersion: v1
kind: Service
metadata:
  name: visioncloud-frontend
  namespace: visioncloud
spec:
  selector:
    app: visioncloud-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
